FROM python:3.9.16-slim AS builder

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-model.txt .

RUN pip install --no-cache-dir --prefer-binary -r requirements-model.txt

COPY classifier/ ./classifier/
COPY setup.py .

FROM python:3.9.16-slim

WORKDIR /app

COPY --from=builder /usr/local /usr/local
COPY --from=builder /app /app

CMD ["python3", "-m", "classifier.test"]
