FROM python:3.10-slim

WORKDIR /app

COPY requirements-model.txt .
RUN pip install --no-cache-dir -r requirements-model.txt

# Copy only necessary files
COPY setup.py .
COPY __init__.py .
COPY classifier/ ./classifier/

# Set entry point to your classifier
CMD ["python", "-m", "classifier.bert_comparison_2"]