services:
  classifier:
    build:
      context: .
      dockerfile: Dockerfile.model
    image: model
    volumes:
      - ./classifier:/app/classifier  # For saving/loading trained models
      - huggingface_models:/root/.cache/huggingface  # For Hugging Face models
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

volumes:
  practicumx_saved_models:
  huggingface_models: