# docker-compose.yml
version: '3.8'
services:
  backend:
    build: ./serverside-main
    ports:
      - "8000:8000"
    volumes:
      - ./serverside-main:/app
    deploy:
      resources:
        limits:
          memory: 512M
  
  frontend:
    build: ./clientside-main
    ports:
      - "80:80"
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 256M