services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=tagger_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 256M

  backend:
    build: ./serverside
    ports:
      - "8080:8080"
    volumes:
      - ./serverside:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db:5432/tagger_db
    deploy:
      resources:
        limits:
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "3"

  frontend-dev:
    build:
      context: ./clientside
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./clientside:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  postgres_data:
