# docker-compose.yml
version: "3.8"
services:
  backend:
    build: ./serverside
    ports:
      - "8000:8000"
    volumes:
      - ./serverside:/app
    deploy:
      resources:
        limits:
          memory: 512M

  frontend:
    build: ./clientside
    ports:
      - "80:80"
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 256M
