version: "3.8"
services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=tagger_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 256M
          
  backend:
    build: ./serverside
    ports:
      - "8000:8000"
    volumes:
      - ./serverside:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db:5432/tagger_db
    deploy:
      resources:
        limits:
          memory: 512M
          
  frontend:
    build: ./clientside
    ports:
      - "80:80"
    volumes:
      - ./clientside:/app
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  postgres_data: